import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

export interface ResourceDescriptor {
  id: string;
  name: string;
  description: string;
  mimeType: string;
  data: unknown;
}

export interface GenerateSDKOptions {
  outputDir: string;
  resources: ResourceDescriptor[];
  logger?: Pick<Console, "info" | "warn" | "error">;
}

function stringify(value: unknown) {
  return JSON.stringify(value, null, 2);
}

export async function generateTypeScriptSDK({
  outputDir,
  resources,
  logger = console,
}: GenerateSDKOptions) {
  await mkdir(outputDir, { recursive: true });

  const entityResource = resources.find((resource) => resource.id === "schema.entityTypes");
  const configResource = resources.find((resource) => resource.id === "config.exported");

  const lines: string[] = [
    "// This file is auto-generated by the DriftCore agent runner.",
    "// Do not edit directly; regenerate via the agent orchestration pipeline.",
    "", "export interface EntityField {",
    "  name: string;",
    "  type: string;",
    "  description: string;",
    "}",
    "",
    "export interface EntityType {",
    "  machineName: string;",
    "  label: string;",
    "  description: string;",
    "  fields: EntityField[];",
    "}",
  ];

  lines.push(
    "",
    "export const entityTypes: EntityType[] = "+
      (entityResource ? stringify((entityResource.data as { entityTypes?: unknown })?.entityTypes ?? []) : "[]") +
      " as const;"
  );

  lines.push(
    "",
    "export const exportedConfiguration = "+
      (configResource ? stringify(configResource.data) : "{}") +
      " as const;"
  );

  const outputPath = path.join(outputDir, "driftcore-sdk.ts");
  await writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
  logger.info?.(`Generated DriftCore SDK at ${outputPath}`);
}
